# Generated by Django 4.2.1 on 2023-05-23 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletins', '0002_alter_bulletin_bul_author_alter_bulletin_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulletin',
            name='category',
            field=models.CharField(choices=[('Танки', 'Танки'), ('Хилы', 'Хилы'), ('ДД', 'ДД'), ('Торговцы', 'Торговцы'), ('Гилдмастеры', 'Гилдмастеры'), ('Квестгиверы', 'Квестгиверы'), ('Кузнецы', 'Кузнецы'), ('Кожевники', 'Кожевники'), ('Зельевары', 'Зельевары'), ('Мастера заклинаний', 'Мастера заклинаний')], max_length=50),
        ),
    ]
