# Generated by Django 4.2.1 on 2023-05-31 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletins', '0004_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='accept',
            field=models.BooleanField(default=False),
        ),
    ]
