# Generated by Django 4.2.1 on 2023-06-05 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bulletins', '0005_reply_accept'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersubscribers',
            name='sub_connect',
        ),
        migrations.RemoveField(
            model_name='usersubscribers',
            name='user_connect',
        ),
        migrations.DeleteModel(
            name='Subscribers',
        ),
        migrations.DeleteModel(
            name='UserSubscribers',
        ),
    ]
