# Generated by Django 4.2.1 on 2023-06-10 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bulletins', '0009_alter_bulletin_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bulletin',
            options={},
        ),
    ]
