# Generated by Django 4.2.1 on 2023-06-10 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletins', '0010_alter_bulletin_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulletin',
            name='category',
            field=models.CharField(choices=[('Танки', 'Танки'), ('Хилы', 'Хилы'), ('ДД', 'ДД'), ('Торговцы', 'Торговцы'), ('Гилдмастеры', 'Гилдмастеры'), ('Квестгиверы', 'Квестгиверы'), ('Кузнецы', 'Кузнецы'), ('Кожевники', 'Кожевники'), ('Зельевары', 'Зельевары'), ('Мастера заклинаний', 'Мастера заклинаний')], default='Танки', max_length=50),
        ),
    ]
