# Generated by Django 4.2.1 on 2023-06-10 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletins', '0011_alter_bulletin_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulletin',
            name='bul_short_description',
            field=models.CharField(default='...', max_length=100),
        ),
        migrations.AddField(
            model_name='news',
            name='news_short_description',
            field=models.CharField(default='...', max_length=100),
        ),
    ]
